### ISSUE TITLE
fetchDirections nhận đường đi bị lệch

### ISSUE THREAD

**Issue by saladle14** [map4d/map4d-services-flutter#5]
Cho mình hỏi Tại sao mình dùng sevice **fetchDirections** mà thấy đường đi trả về nó hơi bị lệch một chút ở những đoạn đường cong nhỉ?

![image](https://user-images.githubusercontent.com/99127189/202111013-17958b65-1366-44e0-996c-25e99c6f13db.png)
![image](https://user-images.githubusercontent.com/99127189/202111342-1c4be42d-6696-41bd-8126-6f731a6b121a.png)

**Comment by nguyenloki258** [comment]
Quan tâm ạ

**Comment by omyto** [comment]
Hi @saladle ,

Có phải bạn tạo **routes** cho DirectionsRenderer từ _startLocation_ và _endLocation_ của các **step** được trả về từ **_fetchDirections_** phải không?
Nếu như vậy thì sẽ thiếu một số điểm chi tiết cho mỗi **step**. Dữ liệu các điểm đó được mã hóa trong _encodedPolyline_, theo cấu trúc của [google-esque polyline](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)

Bạn cần giải mã polyline này và ghép nối vào **routes** thì sẽ hiển thị chính xác đường cong như mong muốn.

Để thuận tiện thì trong tuần tới bên mình sẽ update lib và example hỗ trợ việc tạo **routes** cho DirectionsRenderer từ kết quả trả về từ **_fetchDirections_**
Bạn có thể tự giải mã để xử lý hoặc vui lòng đợi một thời gian nữa.

Thanks

**Comment by saladle14** [comment]
Mình hiểu rồi. Cảm ơn bạn nha.

**Comment by saladle14** [comment]
À mình thấy có 1 vấn đề nữa. Khi mình thay đổi **MFTravelMode**  thì thấy các kết quả trả về vẫn giống nhau.

**Comment by omyto** [comment]
> À mình thấy có 1 vấn đề nữa. Khi mình thay đổi **MFTravelMode** thì thấy các kết quả trả về vẫn giống nhau.

Thông tin **duration** cũng giống nhau à bạn?
Bên mình sẽ kiểm tra lại vấn đề này xem sao.

Thanks
